"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
result = _productService.getByID(2);
var p = new Product_1.Product();
p.id = 2;
p.name = "Iphone 12";
p.category = "IOS";
p.price = 5000;
_productService.saveProduct(p);
// _productService.deleteProduct(result);
result = _productService.getProducts();
console.log(result);
